name: Build BE service - PR check

on:
  pull_request:
    branches: [master, major*, minor*]
    types: [opened, reopened, synchronize, edited]



jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set Berlin Timezone
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Europe/Berlin"

      - name: Checkout project sources
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run build with Gradle Wrapper
        run: |
          cd core
          chmod +x ../gradlew
          ../gradlew build
